#!/usr/bin/env bash

set -e

echo "Trying to cache the root image."
echo "====================================================================="
docker pull alpine:latest \
    && echo "Root image cahed successfully." \
    || echo "Could not cache root image, continuing with what I have."
echo "====================================================================="

echo ""
echo "Compiling"
echo "====================================================================="
before=$(date +"%s")
CGO_ENABLED=0 GOOS=linux go build && echo "Compiled success."
file_timestamp=$(date -r "brisca.sh" +"%s")
if [ $before -ge $file_timestamp ]; then 
    echo "brisca.sh file is stale. Probably it didn't build." >&2
    exit 1
fi
echo "====================================================================="

echo ""
echo "Building docker image"
echo "====================================================================="
docker build -t brisca-twoserver .
echo "====================================================================="
